### ISSUE TITLE
後攻：RESET押しても後攻のターンからになってしまう

### ISSUE THREAD

**Issue by yana33** [yana33/3mokunarabe#2]
自分が後攻の場合、RESETをおしたらはじめに◯が自動で打たれなければいけないのに、×からはじまってしまう。

**Comment by miura-t2r** [comment]
1. RESETボタンをクリックしたイベント処理の内で、
2. ボタンをまっさらにする処理の後に、
3. 先攻か後攻かを判別して、
4. 後攻なら◯を打つメソッドを呼び出しましょう。

**Comment by yana33** [comment]
本日もお忙しい中、有り難うございました。

Pullrequestの内容を確認致しました。
次回、修正させていただきますので、よろしくお願い致します。
